version: "3.3"
services:
  mysql:
    image: mysql:8.0.1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      TZ: America/Manaus
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8082:80
    links:
      - mysql:db
  php7_3:
    image: cbcarlos7/php73
    container_name: php7_3
    volumes:
      - ./backend:/var/www/html
      - ./config/backend/php.ini:/usr/local/etc/php/conf.d/production.ini
      - ./config/backend/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - 8002:8080
    depends_on:
      - mysql
  servidor:
    image: cbcarlos7/php73
    container_name: servidor
    volumes:
      - ./www:/var/www/html
    ports:
      - 81:8080
networks:
  default:
    name: mysql-network
    external: true      
